import { Crop, Transaction, MandiRate, FertilizerTask, GovernmentScheme, HarvestReminder } from './types';

export const INITIAL_CROPS: Crop[] = [
  {
    id: 'crop_1',
    name: 'Wheat',
    area: 2.5,
    date: '12 Nov 2024',
    status: 'Growing',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCwICcB419vZH65DuV89Gk1yDIo4ATw9onc6r5QC7HEGu_8DcSKUlafHhT8748yDzOy-YyHapLpnly4AKxoHoOY4tE_eVsb029tsgL8sOkhs0AHYnPckkn1zIIE3qtM4mDDD18Y8sw33fLcL8KlOHt4g2_hRFcLlibJxowPV0PuLNmQmR6vIH1313c6z-o17zZuxCzQuHWttNA4Y8BunGzieKtk99ZYwcs3lXdXW9nFHBnf4BntqF-OZ163XyP5XkIAIAqTTIltRknV',
    type: 'wheat',
    expectedYield: 18,
    totalCost: 12500,
    marketPrice: 2200
  },
  {
    id: 'crop_2',
    name: 'Paddy',
    area: 1.8,
    date: '05 Jun 2024',
    status: 'Growing',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBM3OkKcTXxE0A_vhgmBtfNfLj_YP6tDjN1c0BrRPatoFzknnFmdO5lVAS3qJaHt1b6mqgDr_ykOCyYpioXmG6HrzHwINi2T4NE28Ap6D-sBbbPMZypuELyAzN-tsAz6LCdXMMnW2UXB5dJUiCxL2-UYDMm1xr1tfy4dTxkmHM58qrmOp5W_UBpi1ahg4mMgzLD4tE9iJlAqje0g-pNWUybozESODsp1a7UY_00bbpxY9FntOldKLeUlJKOSi4sOj4o3IqOwfHANEpF',
    type: 'paddy',
    expectedYield: 15,
    totalCost: 11000,
    marketPrice: 3800
  },
  {
    id: 'crop_3',
    name: 'Soybean',
    area: 1.2,
    date: '20 May 2024',
    status: 'Sowing',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUXhtzWbYzIRLuhfje_-e__dnS8-tde72m59kzeDkiVCEYTddkzfAmXNS16BupOOcPovMM8of2FANdGWFnXsU2Xtk-hP9NdZzkYYTPTHiGV_CvEa-EGpNowPIASpid__wNSl8o2Bkp7NjvzECj0vKtXwUbhONwmh0_utuyNpJm3l5aWSIjV4B31IrIHBNxoAhCJvPnPDLkJYtjRghN_0fVTzwcAZyDjesh-PV8KuANSyzlvEGLGprgh9-YyYG_UAhCNPGXjnsWgRcz',
    type: 'soybean',
    expectedYield: 12,
    totalCost: 8500,
    marketPrice: 4200
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 't_1',
    title: 'Wheat Sale',
    type: 'income',
    amount: 25000,
    date: '12 Nov 2024',
    category: 'crop_sale'
  },
  {
    id: 't_2',
    title: 'Paddy Sale',
    type: 'income',
    amount: 15500,
    date: '08 Nov 2024',
    category: 'crop_sale'
  },
  {
    id: 't_3',
    title: 'Fertilizer',
    type: 'expense',
    amount: 4200,
    date: '05 Nov 2024',
    category: 'fertilizer'
  },
  {
    id: 't_4',
    title: 'Pesticide',
    type: 'expense',
    amount: 3150,
    date: '02 Nov 2024',
    category: 'pesticide'
  },
  {
    id: 't_5',
    title: 'Labor Cost',
    type: 'expense',
    amount: 5410,
    date: '01 Nov 2024',
    category: 'labor'
  }
];

export const INITIAL_MANDI_RATES: MandiRate[] = [
  {
    id: 'm_1',
    commodity: 'Wheat',
    currentPrice: 2450,
    minPrice: 2380,
    maxPrice: 2610,
    change: -25,
    changeType: 'down',
    trendPercentage: 2.4
  },
  {
    id: 'm_2',
    commodity: 'Paddy (Basmati)',
    currentPrice: 3890,
    minPrice: 3600,
    maxPrice: 4150,
    change: 120,
    changeType: 'up',
    trendPercentage: 3.8
  },
  {
    id: 'm_3',
    commodity: 'Soybean',
    currentPrice: 4200,
    minPrice: 4150,
    maxPrice: 4350,
    change: 0,
    changeType: 'stable',
    trendPercentage: 1.2
  },
  {
    id: 'm_4',
    commodity: 'Onion',
    currentPrice: 2800,
    minPrice: 1200,
    maxPrice: 3500,
    change: 450,
    changeType: 'up',
    trendPercentage: 4.5
  }
];

export const INITIAL_FERTILIZER_TASKS: FertilizerTask[] = [
  {
    id: 'task_1',
    title: 'Urea Application',
    dayNum: 42,
    stage: 'Tillering Stage',
    dosage: '45 kg / Acre',
    method: 'Top Dressing',
    status: 'Overdue',
    statusBadge: 'MISSING',
    notes: 'Important for nitrogen boost during crucial growing phase.',
    category: 'fertilizer'
  },
  {
    id: 'task_2',
    title: 'Neem Oil Spray',
    dayNum: 45,
    stage: 'Tillering Stage',
    dosage: '500 ml / Acre',
    method: 'Foliar Spray',
    status: 'Scheduled',
    statusBadge: 'READY',
    notes: 'Preventive measure for aphids and rust control.',
    category: 'spray'
  },
  {
    id: 'task_3',
    title: 'NPK 19-19-19 Booster',
    dayNum: 60,
    stage: 'Booting Stage',
    dosage: '5 kg / Acre',
    method: 'Drip Animation / Foliar Spray',
    status: 'Upcoming',
    statusBadge: 'PLANNED',
    notes: 'Provides balanced nourishment prior to reproduction phase.',
    category: 'booster'
  }
];

export const INITIAL_SCHEMES: GovernmentScheme[] = [
  {
    id: 'scheme_1',
    title: 'PM-Kisan Samman Nidhi',
    description: 'Direct income support of ₹6,000 per year in three equal installments to all landholding farmer families.',
    benefit: '₹6,000 / year',
    eligibility: 'All Landholders',
    subsidy: 'Direct Credit',
    deadline: 'Ongoing',
    category: 'Subsidies',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAtbYezXf04HVPn-dAeZm1iZFAjISaOp1BXg2I_O5TxVw0EXyHbIBhgG9PwFQV_pHS2ZmG0taZC6QhebmFq_qC1HcIoEzHHDZJNZbmZ4vOj-ehxlGd1yXAZ1LMHoFyu2B9y56-Hgipxuq6wMgL_f7nu12_92FwlEmLTmBXcoCc1kx4LzX4B3BKPpy1CCceEFODU9uMfAx6Rh_ljHk7IniLTurup8AULzzgS6iaUJpqwOkABjT9Qt6DlXlGUOQbb1Muu-UWGX6Br5M4B',
    popular: true
  },
  {
    id: 'scheme_2',
    title: 'PM Fasal Bima Yojana',
    description: 'Comprehensive crop insurance against non-preventable natural risks from pre-sowing to post-harvest.',
    benefit: '100% Crop Insurance Cover',
    eligibility: 'Cereal, Oilseeds & Commercial',
    subsidy: 'Pradhan Mantri Premium',
    deadline: 'Jul 31, 2025',
    category: 'Insurance',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuARVFstwItCjOrQpMQOBJHWdrh-HLSD4YZ4GWcBZ97P5guacVNzA2SE_8OG4Kjspn-ieuw7RKa352pdQOAV78m_OjoGUU3UoUayw_dUN6h1q6E9jDnBpX_wn6a1bX50M0C4Udh9CKoSMxLsjq-uWXSpN4iofxfwOyiCk4crRSamZzPsu5uy6PeyUy_Ocvi_9AXlbS35pCXdOXd6YYj1Q59-KO-PTEj4yiag_KyCFTbjLYgouobDybX1dZPNl0IWH7ZLwxy-uhZedCsb'
  },
  {
    id: 'scheme_3',
    title: 'Pradhan Mantri Krishi Sinchayee Yojana',
    description: 'Har Khet Ko Pani - Providing end-to-end solutions in irrigation supply chain and water use efficiency.',
    benefit: 'Deep subsidization on drip equipment',
    eligibility: 'Small & Marginal farmers',
    subsidy: 'Up to 55%',
    deadline: 'Mar 31, 2025',
    category: 'Irrigation',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBM3OkKcTXxE0A_vhgmBtfNfLj_YP6tDjN1c0BrRPatoFzknnFmdO5lVAS3qJaHt1b6mqgDr_ykOCyYpioXmG6HrzHwINi2T4NE28Ap6D-sBbbPMZypuELyAzN-tsAz6LCdXMMnW2UXB5dJUiCxL2-UYDMm1xr1tfy4dTxkmHM58qrmOp5W_UBpi1ahg4mMgzLD4tE9iJlAqje0g-pNWUybozESODsp1a7UY_00bbpxY9FntOldKLeUlJKOSi4sOj4o3IqOwfHANEpF'
  },
  {
    id: 'scheme_4',
    title: 'Agri-Clinic & Agri-Business',
    description: 'Training and financing for agriculture graduates to set up commercial agricultural utility hubs.',
    benefit: 'Soft credit and venture guidance',
    eligibility: 'Agriculture Graduates',
    subsidy: 'Low Interest Loan',
    deadline: 'Dec 31, 2025',
    category: 'Education',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCesRPXuKnGZiHiDSGjES-gSefUHGnTMBt6Zc37CpqzBbyvlIQ-oaNErMIF4QqCobS7AalltWRCIDH-pRKHoGM2r2UBuqTRh4bqIifQANqnAv-IIlONBSaHz9yimnMsqACN4nssX--BbM1H8QvoyFsEZkowFJjTYPRmhshSFmJpGEy6UdTqgeJEAtNWW_687EnoqRLNAsVSjMH-v_ETBfwm4IZcXcNbAzr6YB1dEnZT9g5x3gXiAYCJurIFWhOPJSUQnLp9l8dIJwEv'
  }
];

export const INITIAL_HARVEST_REMINDERS: HarvestReminder[] = [
  {
    id: 'hr_1',
    fieldId: 'Field A-12',
    cropName: 'Wheat (HD-2967)',
    variety: 'HD-2967 A-Grade',
    maturityProgress: 92,
    expectedDate: '15 Mar 2025',
    estimatedYieldRange: '45-50 Qtl',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBMDjrhwiKbJUFaMaLjr1RdyD9YyEznt1SzqghYNB5pNXn5OC7qvIkdDwKjdWFunw8z6jxP_rX36iwMAaOqc6ptiTMhjxSE6B6SF9JQ5qO4Y1g0-EO_A_LdU_loo1oYek61MAz9134GYiVBpSYJQaoL2WKjHQkZA1hPLJBEuUcTa13WVyg-ScCeIXemYulAv1gXcUO47rrsEyISZXfkmBQV6yCEwnmpC_AOQHTKQupKab0Fm_Pvxq3G0jpJw0DoI8wnJlm7RY7zyhgi',
    checklist: [
      { id: 'c_1', text: 'Equipment Service Check', subtext: 'Combine harvester and tractors ready', checked: true, icon: 'Settings' },
      { id: 'c_2', text: 'Labor Arrangement', subtext: 'Confirm 8 members for collection', checked: false, icon: 'Users' },
      { id: 'c_3', text: 'Mandi Space Booking', subtext: 'Slot at Grain Market - Block B', checked: false, icon: 'Store' },
      { id: 'c_4', text: 'Transport Readiness', subtext: '2 Trolleys and covers prepared', checked: false, icon: 'Truck' }
    ]
  },
  {
    id: 'hr_2',
    fieldId: 'Field C-04',
    cropName: 'Paddy (Basmati)',
    variety: 'Basmati Pusa-1121',
    maturityProgress: 78,
    expectedDate: '28 Mar 2025',
    estimatedYieldRange: '32-35 Qtl',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDzve-nD_8FVif0iiOiPcrNBTRjyFxfBwMcAWJTAjkFc6wdOoK-m_ITSbgB_XKv9wm0vvTkJUTBvEupBaFGggJSNufcfOwXyYDl0Sm2pP1JNHPmcNv__ClFyofbng2iHG0At3ZC214ujIfvpYgWdS-rFcziJvZ4UWGzHdZjJiEHxbu-g9eJ5RA0hjTFhkGJpL0nevFXz4RiXdgd-qnrxnkA8bHaTtkvfJXJzqiQmmfxAGJeguz0V_Cdr1Y0wgQR8SwGvBmmkzJfnt8t',
    checklist: [
      { id: 'c2_1', text: 'Harvest Timing Verification', subtext: 'Verify moisture content below 14%', checked: false, icon: 'Droplet' },
      { id: 'c2_2', text: 'Clean Storage Space', subtext: 'Disinfect crop bags and warehouse silos', checked: false, icon: 'Home' }
    ]
  }
];

export const DICTIONARY = {
  English: {
    title: 'Kisan Record',
    subtitle: 'Smart Farming, Digital Records & Higher Profits',
    welcome: 'Namaste, Ramesh',
    location: 'Madhya Pradesh, India',
    humidity: 'Humidity',
    wind: 'Wind',
    rain: 'Rain',
    quick_actions: 'Quick Actions',
    my_farm: 'My Farm',
    crop_record: 'Crop Record',
    expenses: 'Expenses',
    income: 'Income',
    fertilizer: 'Fertilizer',
    weather: 'Weather',
    market_price: 'Market Price',
    schemes: 'Schemes',
    calculator: 'Calculator',
    kisan_suvidha: 'Kisan Suvidha',
    suvidha_tag: 'All farming solutions in one app. Free guidance for better yield.',
    recent_activities: 'Recent Activities',
    view_all: 'View All',
    back: 'Back',
    all_crops: 'All crops',
    current: 'Current',
    completed: 'Completed',
    add_crop: 'Add Crop',
    status: 'Status',
    growing: 'Growing',
    sowing: 'Sowing',
    this_month: 'This Month',
    this_year: 'This Year',
    custom: 'Custom',
    total_income: 'Total Income',
    total_expenses: 'Total Expenses',
    transactions: 'Transactions',
    add_transaction: 'Add Transaction',
    equipment_savings: 'Equipment Savings',
    saving_goal: "You're 65% closer to your new tractor goal!",
    crop_price_trend: 'Crop Price Trend',
    nearby_mandis: 'Nearby Mandis',
    favorite_crops: 'Favorite Crops',
    state_wide: 'State-wide',
    mandi_source_note: '* Rates are updated daily from official AGMARKNET and Mandi board sources. Prices shown are for average quality arrivals.',
    lowest_7d: 'LOWEST (7D)',
    highest_7d: 'HIGHEST (7D)',
    market_rates_today: 'Market Rates Today',
    sort_by: 'Sort by',
    per_quintal: 'per Quintal',
    calculated_results: 'Calculated Results',
    total_yield: 'Total Yield',
    gross_income: 'Gross Income',
    total_cost: 'Total Cost',
    estimated_profit: 'Estimated Profit',
    calculate_again: 'Calculate Again',
    calculation_summary: 'Calculation Summary',
    calculator_helper: 'Prices and yields are estimates. Market prices fluctuate based on quality and local Mandi rates.',
    personal_info: 'Personal Information',
    farm_details: 'Farm Details',
    app_settings: 'App Settings',
    dark_mode: 'Dark Mode',
    notifications: 'Notifications',
    support_info: 'Support & Info',
    help_center: 'Help Center',
    privacy_policy: 'Privacy Policy',
    log_out: 'Log Out',
    admin_panel: 'Admin Panel',
    username_email: 'Username/Email',
    password: 'Password',
    remember_me: 'Remember Me',
    forgot_password: 'Forgot Password?',
    login: 'Login',
    secure_connection_note: 'End-to-End Encrypted Secure Connection',
    harvest_reminders: 'Harvest Reminders',
    advisory: 'Weather Advisory',
    advisory_desc: 'Light showers expected in 48 hours. Ensure your harvest collection area is covered and equipment is shielded.',
    readiness_checklist: 'Readiness Checklist',
    preparation: 'Preparation for',
    add_custom_task: 'Add Custom Task',
    generate_reports: 'Generate Reports',
    quick_export: 'Quick Export',
    custom_report_builder: 'Custom Report Builder',
    select_date_range: 'Select Date Range',
    report_type: 'Report Type',
    export_format: 'Export Format',
    recent_downloads: 'Recent Downloads',
    generate_custom_report: 'Generate Custom Report',
    optimal_weather: 'Optimal Weather',
    optimal_weather_desc: 'Clear sky for the next 48h. Ideal for foliar spray today.',
    need_help_applying: 'Need help applying?',
    need_help_desc: 'Visit your nearest Kisan Suvidha center or call our toll-free helpline.',
    call_helpline: 'Call 1800-XXX-XXXX',
    all_schemes: 'All Schemes',
    subsidies: 'Subsidies',
    insurance: 'Insurance',
    irrigation: 'Irrigation',
    education: 'Education',
    popular: 'Popular',
    view_details: 'View Details',
    check_details: 'Check Details',
    learn_more: 'Learn More',
    search_schemes: 'Search schemes by name or keyword...',
    search_crops_mandis: 'Search crops or mandis...'
  },
  Hindi: {
    title: 'किसान रिकॉर्ड',
    subtitle: 'स्मार्ट खेती, डिजिटल रिकॉर्ड और अधिक लाभ',
    welcome: 'नमस्ते, रमेश',
    location: 'मध्य प्रदेश, भारत',
    humidity: 'आर्द्रता',
    wind: 'हवा',
    rain: 'बारिश',
    quick_actions: 'त्वरित विकल्प',
    my_farm: 'मेरा खेत',
    crop_record: 'फसल रिकॉर्ड',
    expenses: 'खर्चे',
    income: 'आय',
    fertilizer: 'उर्वरक',
    weather: 'मौसम',
    market_price: 'बाजार भाव',
    schemes: 'सरकारी योजनाएं',
    calculator: 'कैलकुलेटर',
    kisan_suvidha: 'किसान सुविधा',
    suvidha_tag: 'एक ही ऐप में खेती के सभी समाधान। बेहतर उपज के लिए मुफ्त मार्गदर्शन।',
    recent_activities: 'हाल की गतिविधियां',
    view_all: 'सभी देखें',
    back: 'पीछे',
    all_crops: 'सभी फसलें',
    current: 'वर्तमान',
    completed: 'पूर्ण',
    add_crop: 'फसल जोड़ें',
    status: 'स्थिति',
    growing: 'बढ़ रही है',
    sowing: 'बुवाई',
    this_month: 'इस महीने',
    this_year: 'इस साल',
    custom: 'कस्टम',
    total_income: 'कुल आय',
    total_expenses: 'कुल खर्च',
    transactions: 'लेनदेन',
    add_transaction: 'लेनदेन जोड़ें',
    equipment_savings: 'उपकरण बचत',
    saving_goal: 'आप अपने नए ट्रैक्टर लक्ष्य के ६५% करीब हैं!',
    crop_price_trend: 'फसल मूल्य रुझान',
    nearby_mandis: 'निकटतम मंडियां',
    favorite_crops: 'पसंदीदा फसलें',
    state_wide: 'राज्य स्तर पर',
    mandi_source_note: '* दरें आधिकारिक AGMARKNET और मंडी बोर्ड स्रोतों से दैनिक रूप से अपडेट की जाती हैं। दिखाए गए मूल्य औसत गुणवत्ता के हैं।',
    lowest_7d: 'न्यूनतम (7 दिन)',
    highest_7d: 'अधिकतम (7 दिन)',
    market_rates_today: 'आज के बाजार भाव',
    sort_by: 'क्रमबद्ध करें',
    per_quintal: 'प्रति क्विंटल',
    calculated_results: 'गणना के परिणाम',
    total_yield: 'कुल उपज',
    gross_income: 'सकल आय',
    total_cost: 'कुल लागत',
    estimated_profit: 'अनुमानित लाभ',
    calculate_again: 'फिर से गणना करें',
    calculation_summary: 'गणना सारांश',
    calculator_helper: 'मूल्य और उपज अनुमानित हैं। गुणवत्ता और स्थानीय मंडी दरों के आधार पर बाजार मूल्य में उतार-चढ़ाव होता है।',
    personal_info: 'व्यक्तिगत जानकारी',
    farm_details: 'खेत का विवरण',
    app_settings: 'ऐप सेटिंग',
    dark_mode: 'डार्क मोड',
    notifications: 'सूचनाएं',
    support_info: 'सहायता और जानकारी',
    help_center: 'सहायता केंद्र',
    privacy_policy: 'गोपनीयता नीति',
    log_out: 'लॉग आउट',
    admin_panel: 'प्रशासक पैनल',
    username_email: 'यूज़रनेम / ईमेल',
    password: 'पासवर्ड',
    remember_me: 'याद रखें',
    forgot_password: 'पासवर्ड भूल गए?',
    login: 'लॉगिन',
    secure_connection_note: 'एंड-टू-एंड एन्क्रिप्टेड सुरक्षित कनेक्शन',
    harvest_reminders: 'कटाई अनुस्मारक',
    advisory: 'मौसम की चेतावनी',
    advisory_desc: '४८ घंटों में हल्की बारिश की संभावना। सुनिश्चित करें कि कटाई संग्रहण क्षेत्र ढका हुआ है।',
    readiness_checklist: 'कटाई तैयारी चेकलिस्ट',
    preparation: 'तैयारी फसल',
    add_custom_task: 'कार्य जोड़ें',
    generate_reports: 'रिपोर्ट बनाएं',
    quick_export: 'तुरंत डाउनलोड',
    custom_report_builder: 'कस्टम रिपोर्ट बिल्डर',
    select_date_range: 'विवरण तिथि सीमा',
    report_type: 'रिपोर्ट का प्रकार',
    export_format: 'फाइल फॉर्मेट',
    recent_downloads: 'हाल के डाउनलोड',
    generate_custom_report: 'कस्टम रिपोर्ट तैयार करें',
    optimal_weather: 'सर्वोत्तम मौसम',
    optimal_weather_desc: 'अगले ४८ घंटे तक आसमान साफ। आज छिड़काव के लिए आदर्श दिन है।',
    need_help_applying: 'आवेदन में मदद चाहिए?',
    need_help_desc: 'अपने नजदीकी किसान सुविधा केंद्र पर जाएं या टोल-फ्री हेल्पलाइन पर कॉल करें।',
    call_helpline: 'कॉल करें 1800-XXX-XXXX',
    all_schemes: 'सभी योजनाएं',
    subsidies: 'सब्सिडी',
    insurance: 'बीमा सुरक्षा',
    irrigation: 'सिंचाई व्यवस्था',
    education: 'कृषि शिक्षा',
    popular: 'प्रसिद्ध',
    view_details: 'विवरण देखें',
    check_details: 'विवरण जांचें',
    learn_more: 'अधिक जानें',
    search_schemes: 'स्कीम या कीवर्ड द्वारा खोजें...',
    search_crops_mandis: 'फसल या मंडी खोजें...'
  }
};
